baseURL: "https://rethinkr-hub.github.io/blog/"
title: Rethinkr    
paginate: 5
theme: ["PaperMod"]

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-1Z3F8KWJWN

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  title: Rethinkr Blog
  description: "A blog exploring data architecture and AI with reproducible tutorials beyond the surface level"
  keywords: [Blog, Portfolio, PaperMod]
  mainSections: ["data-simulators", "pub-sub"]
  author: Jason Grein
  # author: ["Me", "You"] # multiple authors
  images: ["img/blog-home-logo.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: img/fav-icon.png
    favicon16x16: img/fav-icon-16.png
    favicon32x32: img/fav-icon-32.png
    apple_touch_icon: img/fav-icon-32.png
    safari_pinned_tab: img/fav-icon-32.png

  label:
    text: "Home"
    icon: img/blog-nav-logo.png
    iconHeight: 40

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Rethinkr Blog
    subtitle: "Rethinking Data Architecture with Reproducible Examples"
    imageUrl: "img/blog-home-logo.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Rethinkr Logo
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: Data Architecture Blog
    Content: A blog that delves into the fascinating world of data architecture and artificial intelligence (AI) with reproducible tutorials that explore beyond the *Hello World* surface level

  socialIcons:
    - name: twitter
      url: "https://twitter.com/"
    - name: stackoverflow
      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/rethinkr-hub/blog"

  analytics:
    google:
      SiteVerificationTag: "G-1Z3F8KWJWN"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/rethinkr-hub/blog/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 5
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: about
      name: About
      url: /about/
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    # noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai